## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('protean-evaluation',
                                 ['point-to-point', 'traffic-control', 'internet', 'applications'])
    obj.source = ['protean-evaluation.cc', 'cdf.c']
    obj = bld.create_ns3_program('protean-evaluation-simple',
                                 ['point-to-point', 'traffic-control', 'internet', 'applications'])
    obj.source = ['protean-evaluation-simple.cc', 'cdf.c']
    obj = bld.create_ns3_program('protean-evaluation-motivation',
                                 ['point-to-point', 'traffic-control', 'internet', 'applications'])
    obj.source = ['protean-evaluation-motivation.cc', 'cdf.c']
